name: Update Projects Display
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-projects:
    name: Update README with latest project updates  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with repository cards
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: pr1m8
          template: repository
          base: ""
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_forks: no
          plugin_repositories_affiliations: owner, collaborator
          repositories_batch: 6
          filename: projects-metrics.svg
          
      - name: Commit generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add projects-metrics.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update projects metrics

            🤖 Generated with GitHub Actions"
            git push
          fi